# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treesync < Formula
  desc "Live-sync a git worktree's changes into another worktree on a detached HEAD"
  homepage "https://github.com/rcwsr/treesync"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.3/treesync_0.0.3_darwin_amd64.tar.gz"
      sha256 "d5cf282efb736bf0e76203aab926f2230944003529f0710d3ec04e79579e4c71"

      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.3/treesync_0.0.3_darwin_arm64.tar.gz"
      sha256 "a488067166095c632d875f97242dbd2db70ad54d07edd4de55e692095bbcef7f"

      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.3/treesync_0.0.3_linux_amd64.tar.gz"
      sha256 "5cc25b602b53f52eb1fe4c54a57f8be0da60b562a2dfbfaa58441c63f5d4a2c1"
      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.3/treesync_0.0.3_linux_arm64.tar.gz"
      sha256 "aa8c09130930081ff32a9219911461ae61fc828e9c5963e92410f53e7d7efe66"
      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  test do
    system "#{bin}/treesync --version"
  end
end
