# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treesync < Formula
  desc "Live-sync a git worktree's changes into another worktree on a detached HEAD"
  homepage "https://github.com/rcwsr/treesync"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.2/treesync_0.0.2_darwin_amd64.tar.gz"
      sha256 "8da284d556516265a54e173c6cca665a47bb7ccc42cf20ecb8af82f7e4fc56f9"

      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.2/treesync_0.0.2_darwin_arm64.tar.gz"
      sha256 "d9c5abddfbc43859bc1674365212be5a102daad9f23ff31fbd89b19dece1d033"

      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.2/treesync_0.0.2_linux_amd64.tar.gz"
      sha256 "0fbabf3aa42facb55ebaf319b363ce2750c2b08f6aa1e15653b72f871f1df045"
      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.2/treesync_0.0.2_linux_arm64.tar.gz"
      sha256 "39d4ee0780b581ab7a6dcb6e2676e5fc84a05f4bd8da3a81c219435a610a9f36"
      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  test do
    system "#{bin}/treesync --version"
  end
end
