# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treesync < Formula
  desc "Live-sync a git worktree's changes into another worktree on a detached HEAD"
  homepage "https://github.com/rcwsr/treesync"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.4/treesync_0.0.4_darwin_amd64.tar.gz"
      sha256 "208f73caeaa12fe2fd0df3d35e54691782720efe4bcc52f63f3d4d088c8d5b3f"

      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.4/treesync_0.0.4_darwin_arm64.tar.gz"
      sha256 "c874bd7b35c0510d898b376db7e942d9b55e82f48e7d935a78994fd0883e42d1"

      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.4/treesync_0.0.4_linux_amd64.tar.gz"
      sha256 "cdc13dc851563f7191e2bd3be7b53de775faa4687040140654a1ddacb1d8b4ed"
      define_method(:install) do
        bin.install "treesync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rcwsr/treesync/releases/download/v0.0.4/treesync_0.0.4_linux_arm64.tar.gz"
      sha256 "78c13be9219988dd1e3d459e513d2cdbbf9ab4a2fb5065f155207f84239b3590"
      define_method(:install) do
        bin.install "treesync"
      end
    end
  end

  test do
    system "#{bin}/treesync --version"
  end
end
